Inline ansi modules
crossterm-rs/crossterm pull request #529
Opened 2020-12-29 13:23 UTC by Koxiaet

Having separate modules that store the ANSI codes makes the codebase harder to read, as there is a layer of indirection. If they are inline, it reduces the number of lines of code, improves the usefullness of the `[src]` button in the documentation, and reduces the amount of jumping around required when reading or editing the code.

2021-01-02 15:00 UTC, TimonPost commented on src/cursor.rs
> +        write!(f, csi!("{};{}H"), self.0 + 1, self.1 + 1)
When debugging I discoverd those arguments should be switched around. 

```rs
write!(f, csi!("{};{}H"), self.1 + 1, self.0 + 1)
```

2021-01-02 15:07 UTC, TimonPost requested changes
Nice changes it does really make it easier to read. During debugging everything still seems to work as supposed except for moving the cursor position.

2021-01-02 15:46 UTC, Koxiaet commented
Ah, that's subtle. It should be fixed now.

2021-01-03 13:29 UTC, merged

2021-01-03 13:29 UTC, TimonPost commented
Thanks!