doc: Make readme more human-sensible at one line
crossterm-rs/crossterm pull request #729
Opened 2022-11-15 03:23 UTC by aaarkid

Line 141: Se/dese/rializing -> De/serializing

2022-11-15 03:24 UTC, aaarkid commented
Just came upon this project by random and found this one line weird. Crate seems very cool!

2022-11-23 13:49 UTC, CenTdemeern1 requested changes

2022-11-23 13:49 UTC, CenTdemeern1 commented on README.md
> +| `serde`        | De/serializing of events.                    |
```suggestion
| `serde`        | Serializing/deserializing of events.         |
```

2022-11-23 19:05 UTC, CenTdemeern1 commented on README.md
> +| `serde`        | De/serializing of events.                    |
Another option:
```suggestion
| `serde`        | (De)serializing of events.                   |
```

2022-12-12 11:26 UTC, CenTdemeern1 commented
@aaarkid Could you please make the requested changes? The PR is getting stale.

2022-12-12 12:19 UTC, aaarkid commented
Sorry, I wasn't aware my action was required. Committed the suggestion.

2022-12-13 15:01 UTC, CenTdemeern1 approved these changes
Thanks!

2022-12-14 12:44 UTC, CenTdemeern1 commented
@TimonPost ?

2023-01-08 13:17 UTC, TimonPost approved these changes
Cool!

2023-01-08 13:17 UTC, merged